services:
  - type: web
    name: floriq-erp
    runtime: docker
    repo: https://github.com/Rufron/flowerErp
    branch: main
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: floriq-db
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
          name: floriq-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: floriq-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: floriq-db
          property: password

databases:
  - name: floriq-db
    databaseName: floriq
    user: floriq_user
    plan: free